### ISSUE TITLE
Validate host before add to blacklist

### ISSUE THREAD

**Issue by mateuspontes** [fastlane-queue/fastlane#14]
Format: `host:port`

Ref: https://github.com/fastlane-queue/fastlane/blob/master/fastlane/worker/docker/api.py#L26-L34

**Comment by endersonmenezes** [comment]
I'm new to collaboration, I will try to create a validation for this!

**Comment by endersonmenezes** [comment]
@mateuspontes Can you put me in doubt, the modifications I made gave all those mistakes even in Trevis?
I'm not an expert with CI/CD, but the with a little read, gave errors in multiple files,I kept asking myself, if I did anything wrong, just to understand ^^
