### ISSUE TITLE
Fix security issues on dependencies

### ISSUE THREAD

**Issue by mateuspontes** [fastlane-queue/fastlane#15]
Some dependencies are outdated and need to be updated asap.

![image](https://user-images.githubusercontent.com/342161/66070249-5b508680-e527-11e9-9182-242f8512f714.png)

**Comment by treviza153** [comment]
I thing I can take it. Wait for my PR!

**Comment by treviza153** [comment]
I think I can take it. Wait for my PR!

**Comment by treviza153** [comment]
#20

**Comment by osmarpetry** [comment]
@mateuspontes where is this `yarn.lock` or `requirements.txt` file? I couldn't find then

**Comment by mateuspontes** [comment]
@osmarpetry fastlane uses Poetry:
`https://github.com/fastlane-queue/fastlane/blob/master/poetry.lock`

**Comment by osmarpetry** [comment]
This PR should fix: https://github.com/fastlane-queue/fastlane/pull/27
